### ISSUE TITLE
How to LaTeX-ing

### ISSUE THREAD

**Issue by ofenerci** [bcrowell/lm#1]
Hello, 
I am currently working on your "Light and Matter" books. I would like to translate a few chapters but it is a little bit over my head to modify the materials. I am trying to figure out macros used in the book. As they are not  conventional LaTeX macros, it is hard for me to decipher their meaning. For example, for including figures you are using the macro below (from your special relativity book, ch.3):

> <%
>   fig(   
>     'twin-signals',
>     %q{The twin paradox with signals sent back to earth by the traveling twin.},
>     {
>       'width'=>'wide','sidecaption'=>true
>     }
>   )
> %>

This code is a little bit cryptic to me. I wonder it is possible to write an instruction how to use macros. Maybe in the future releases of your other books, they may be delivered in well-known LaTeX classes  (your books have similar layouts like Tufte Class: https://github.com/Tufte-LaTeX/tufte-latex). That will ease the transition for the people who want to translate or modify your books. 

Thank you for your superb books.

**Comment by bcrowell** [comment]
These are in ruby, and the documentation is in comments in the file eruby_util.rb.
